use engine_core::physics::world::{PhysicsWorld, PhysicsConfig};
use engine_core::physics::body::{RigidBody, BodyType};
use engine_core::collision::Collider;
use engine_core::collision::gjk::support::{Box as BoxShape};
use engine_core::math::Vector3;

fn main() {
    println!("--- TITAN ENGINE: SILICON-LEVEL TGS SOLVER DEMONSTRATION ---");
    
    // 1. Configure the Temporal Gauss-Seidel (TGS) Environment
    let mut config = PhysicsConfig::default();
    config.sub_steps = 4; // The 'Temporal' in TGS: Breaking the frame into sub-steps
    config.iterations = 12; // The Gauss-Seidel iterations per sub-step
    
    let mut world = PhysicsWorld::new(config);
    
    // 2. Spawn the Bodies (The Cliff / The Tower)
    // Instead of fake 1D math, we use real 3D RigidBodies.
    // The "Tension" will be generated by the Engine's collision constraints (Jacobians).
    
    // T3: The Root Anchor (Static Floor)
    let shape = Collider::Box(BoxShape::new(0.5, 0.5, 0.5));
    let mut t3 = RigidBody::new(Vector3::new(0.0, 0.0, 0.0), shape);
    t3.body_type = BodyType::Static;
    t3.mass_props.inv_mass = 0.0;
    world.add_body(t3); // Handle 0
    
    // T2: Stable Base
    let mut t2 = RigidBody::new(Vector3::new(0.0, 1.0, 0.0), shape);
    t2.body_type = BodyType::Dynamic;
    world.add_body(t2); // Handle 1
    
    // T1: The Grip
    let mut t1 = RigidBody::new(Vector3::new(0.0, 2.0, 0.0), shape);
    t1.body_type = BodyType::Dynamic;
    world.add_body(t1); // Handle 2
    
    // B1: MAIN FOCUS POINT
    let mut b1 = RigidBody::new(Vector3::new(0.0, 3.0, 0.0), shape);
    b1.body_type = BodyType::Dynamic;
    let b1_handle = world.add_body(b1); // Handle 3
    
    // B2: Deadweight
    let mut b2 = RigidBody::new(Vector3::new(0.0, 4.0, 0.0), shape);
    b2.body_type = BodyType::Dynamic;
    world.add_body(b2); // Handle 4
    
    // B3: Tail
    let mut b3 = RigidBody::new(Vector3::new(0.0, 5.0, 0.0), shape);
    b3.body_type = BodyType::Dynamic;
    world.add_body(b3); // Handle 5
    
    println!("Initial Setup Complete. B1 is sandwiched between T1 (Below) and B2 (Above).");
    if let Some(body) = world.get_body(b1_handle) {
        println!("B1 Initial Position Y: {:.4}", body.transform.translation.y());
        println!("B1 Initial Velocity Y: {:.4}", body.velocity.y());
    }

    // 3. Execute the Silicon Behavior (1 Frame = 1/60th second)
    println!("\nExecuting 1 Frame (dt = 0.0166)...");
    println!("Engine will internally compute Jacobians, Effective Mass, and solve the system via TGS.");
    
    let dt = 1.0 / 60.0;
    world.update(dt, None, None);
    
    // 4. Verify Output
    if let Some(body) = world.get_body(b1_handle) {
        println!("\nB1 Final Position Y: {:.6}", body.transform.translation.y());
        println!("B1 Final Velocity Y: {:.6}", body.velocity.y());
        
        let displacement = body.transform.translation.y() - 3.0;
        println!("B1 Total 'Slip' (Displacement due to gravity and constraint resolution): {:.6}", displacement);
    }
    
    println!("------------------------------------------------------------");
}
